# Generated by Django 3.2.7 on 2021-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='ru', max_length=64, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='index',
            field=models.IntegerField(verbose_name='Code for request'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
