# Generated by Django 3.2.7 on 2021-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210929_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
